import 'package:flutter/material.dart';
import '../../../../core/constants/app_dimens.dart';
import '../../../../core/constants/app_text_styles.dart';

/// A single reusable scaffold for any long-form static text screen.
/// Privacy Policy and Terms & Conditions both use this with different
/// [title]/[sections] rather than being two near-duplicate files.
class StaticContentPage extends StatelessWidget {
  const StaticContentPage({
    super.key,
    required this.title,
    required this.sections,
  });

  final String title;

  /// (heading, body) pairs rendered in order.
  final List<(String, String)> sections;

  @override
  Widget build(BuildContext context) {
    final textPrimary = Theme.of(context).colorScheme.onSurface;

    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: ListView(
        padding: const EdgeInsets.all(AppSpacing.lg),
        children: sections.map((section) {
          final (heading, body) = section;
          return Padding(
            padding: const EdgeInsets.only(bottom: AppSpacing.lg),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(heading, style: AppTextStyles.h3(color: textPrimary)),
                const SizedBox(height: 6),
                Text(body, style: AppTextStyles.bodyMedium(color: textPrimary)),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}

const privacyPolicySections = <(String, String)>[
  (
    'Information We Collect',
    'We collect the information you provide directly (name, email, phone, '
        'shipping addresses) and information generated by using the app '
        '(order history, wishlist, browsing activity) to operate NovaCart.',
  ),
  (
    'How We Use Your Information',
    'Your information is used to process orders, provide customer support, '
        'personalize product recommendations, and send order/promotional '
        'notifications you can opt out of at any time.',
  ),
  (
    'Data Security',
    'All data is stored using Firebase\'s secure infrastructure with '
        'per-user access rules — no other user or unauthenticated request can '
        'read your orders, addresses, or wishlist.',
  ),
  (
    'Your Rights',
    'You can edit or delete your personal information, saved addresses, and '
        'account at any time from the Profile section.',
  ),
];

const termsAndConditionsSections = <(String, String)>[
  (
    'Acceptance of Terms',
    'By creating a NovaCart account or placing an order, you agree to these '
        'Terms & Conditions.',
  ),
  (
    'Orders & Payment',
    'All orders are subject to product availability. Prices are shown in '
        'EGP and include any applicable taxes at checkout.',
  ),
  (
    'Shipping & Returns',
    'Estimated delivery windows are shown at checkout. Items may be '
        'returned within 30 days of delivery in original condition.',
  ),
  (
    'Limitation of Liability',
    'NovaCart is not liable for indirect or consequential damages arising '
        'from the use of this app, to the maximum extent permitted by law.',
  ),
];
